@startuml

top to bottom direction
package "User Service" {
    class User {
        +int id
        +string name
        +string email
    }
}

package "Home Service" {
    class House {
        +int id
        +string name
        +int user_id
    }
}

package "Device Service" {
    class Device {
        +uuid id
        +int type_id
        +int house_id
        +string serial_number
        +bool status
        +int module_id
    }

    class DeviceType {
        +int id
        +String name
    }

    class Module {
        +int id
        +String name
    }
    
    note bottom of  Module : Группа устройств
}

package "Telemetry Service" {
    class TelemetryData {
         +uuid id
         +DateTime created_at
         +uuid device_id
         +json data
    }

    note bottom of  TelemetryData : Данные о работе устройств
}

User "1" -- "0..*" House 
House "1" -- "0..*" Device
DeviceType "1" -- "1..*" Device
Module "0..1" -- "0..*" Device 
TelemetryData "0..1" -- "0..*"  Device

@enduml 