@device_service_HostAddress = http://localhost:5224

GET {{sensor_service_HostAddress}}/sensors/
Accept: application/json

###

GET {{sensor_service_HostAddress}}/sensors/1
Accept: application/json

###
